### ISSUE TITLE
RFC: Configure linguist not to ignore node_modules

### ISSUE THREAD

**Issue by rreusser** [stdlib-js/stdlib#91] opened 2017-05-07 00:57 UTC
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue (or feature request).

Github detects a javascript project and collapses any changes in a directory called node_modules when submitting a PR, which I think makes it tedious to review changes. I think it's possible to disable this behavior by configuring [linguist](https://github.com/github/linguist#vendored-code) to treat `lib/node_modules` as *not* vendored (i.e. ignored for the sake of stats and PR review) code.

## Related Issues

> Does this issue (or feature request) have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

Small, important changes get collapsed:

<img width="818" alt="screen shot 2017-05-06 at 17 53 40" src="https://cloud.githubusercontent.com/assets/572717/25777032/0c3a542e-3285-11e7-98b8-7a1dab7328f2.png">

#### Demo

> If relevant, provide a link to a live demo.

* https://github.com/stdlib-js/stdlib/compare/develop...rreusser:feature/factorial2?expand=1

#### Reproduction

> If this issue is a bug report, what steps are required to reproduce the unexpected output? (If this is a feature request, remove this section.)

In order to reproduce this bug, do the following:

* submit a pull request
* view changes

#### Expected Results

> What are the expected results?

Important changes are visible

#### Actual Results

> What are the actual results?

Important changes are collapsed

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by rreusser** [comment] 2017-05-07 01:00
Solving this *might* just be a one-line addition to `.gitattributes` of `lib/node_modules linguist-vendored=false`

**Comment by kgryte** [comment] 2017-05-07 05:17
Addressed via commit https://github.com/stdlib-js/stdlib/commit/20a70436a0f9bb31faaf33cd24ef392f17588935. Can you rebase onto the latest `develop` and see if the issue is resolved?

**Comment by rreusser** [comment] 2017-05-07 05:55
Sad face. Long story short, the juxtaposition of "ignore binary or vendored files and suppress generated files in diffs" suggested specifying vendored files affects diffs. It does do both, but [`gitattributes` files is not available on the front end server](https://github.com/github/linguist/issues/2206#issuecomment-89302292), so this doesn't seem to have any effect.

**Comment by kgryte** [comment] 2017-05-07 06:00
Thanks for linking in that issue thread. Alas, we'll have to resort to inconvenient ergonomics on this one. On the flip side, the ability to "opt-in" to see a diff is handy, especially when only wanting to see which files changed.

**Comment by kgryte** [comment] 2017-05-07 06:02
One side effect of fiddling with `.gitattributes` is that the language statistics are now a bit odd. Need to explore a bit more to see how linguist is determining LOC per file type.

**Comment by rreusser** [comment] 2017-05-07 06:14
It sounds back and forth and unclear and maybe reports of it working temporarily. There's vendored and generated. Maybe that line needs to be `lib/node_modules/* linguist-generated=false`. See: https://github.com/github/linguist/issues/3539#issuecomment-297726042

(Another iteration or two and it'll probably balance out the cost of investigating too much further 😄 )

**Comment by rreusser** [comment] 2017-05-07 06:24
Ah, maybe [this is the line](https://github.com/github/linguist#generated-code):

> As an added bonus, unlike vendored and documentation files, these files are suppressed in diffs.

So maybe it's both vendored and generated and it's marking it not-generated that prevents suppression.

**Comment by kgryte** [comment] 2017-05-07 06:28
Set the pathname attribute in commit https://github.com/stdlib-js/stdlib/commit/885a6fcde76102b90d5ced00fce3ac35d378d439. Perhaps this will work.

**Comment by rreusser** [comment] 2017-05-07 06:31
Worked, thanks! Hopefully doesn't mix up the stats too much. If the stats are okay, I'm perfectly content to consider solved.

**Comment by kgryte** [comment] 2017-05-07 06:32
Awesome. Yeah, not too concerned about GitHub getting the language stats a bit off. We have internal tooling which does more accurate computations. Closing...

**Closed as completed by kgryte** 2017-05-07 06:32 UTC
Labels: Bug
