### ISSUE TITLE
dscal is not a function

### ISSUE THREAD

**Issue by marcospassos** [stdlib-js/stdlib#508] opened 2022-08-29 13:15 UTC
### Description

Encountered an error when calling `chi2gof` with a unity probability array.

### Questions

No.

### Reproduction

```shell
chi2gof([135017, 1533, 13450], [0.9, 0.01, 0.09]);
```

### Expected Results

```shell
No error.
```

### Actual Results

```shell
dscal is not a function
TypeError: dscal is not a function
```
```


### Version

0.0.7

### Environments

Node.js

### Browser Version

_No response_

### Node.js / npm Version

_No response_

### Platform

_No response_

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by marcospassos** [comment] 2022-08-29 13:40
When passing `simulate: true` it gives another error:
```
dsumpw is not a function
```

**Comment by Planeshifter** [comment] 2022-08-29 14:03
Hey there,
To allow us to reproduce the issue, could you please let us know how you are consuming the `chi2gof` package?  
Are you loading one of the pre-built bundles, have you installed the entire library (` npm install @stdlib/stdlib`) or just the package (`npm install @stdlib/stats-chi2gof`) from npm, or something else? Last but not least, did you run the failing commands via Node.js or a similar runtime or do you use a bundler such as Webpack?

**Comment by marcospassos** [comment] 2022-08-29 14:16
The snippet is pretty simple. I'm consuming the `chi2gof` only.

```
import chi2gof from '@stdlib/stats-chi2gof';

chi2gof([135017, 1533, 13450], [0.9, 0.01, 0.09]);
```

And I'm running using the `ts-jest`, no extra config.

**Comment by marcospassos** [comment] 2022-08-29 14:52
@Planeshifter, I took a look more in-depth, and it seems to have something wrong here:

![image](https://user-images.githubusercontent.com/943036/187229798-32b0ef22-60af-4cd3-af3f-0230cfa2fbff.png)

Notice that the `blas-ext-base-dsumpw` imports `addon.node` that doesn't exist in the distribution. The same happens for the `daxpy`, `dscal` and `dsumpw`:

![image](https://user-images.githubusercontent.com/943036/187230207-1b4da742-3852-4a4b-9270-e44e85b713e7.png)

**Comment by marcospassos** [comment] 2022-08-29 15:01
Investigating even further, it seems a generalized issue with all `@stdlib/blas-*` packages.

**Comment by Planeshifter** [comment] 2022-08-29 15:10
Thanks for investigating!

I can reproduce the issue using `ts-jest`. We will discuss internally how to resolve it in due time and post any updates to this thread.

In the meantime, a temporary solution for you would be to add the following to your Jest configuration

```json
  "moduleNameMapper:" {
    "^@stdlib/blas(.*)$": "<rootDir>/node_modules/@stdlib/blas$1/lib/main.js"
  }
 ```

This would ensure that Jest doesn't try to load the missing native add-ons for the `blas` packages but defaults to the JavaScript implementations (I have created a test repository [here](https://github.com/Planeshifter/chi2gof-test).)

**Comment by marcospassos** [comment] 2022-08-29 16:07
Thank you for the workaround. Looking forward to a fix :)

**Comment by kgryte** [comment] 2022-08-29 20:35
@marcospassos Able to track down the issue, which was due to realms and failing `instanceof` checks. Fix committed to main branch. Should be available to individual packages once we do another standalone package release.

**Comment by marcospassos** [comment] 2022-08-29 20:36
Thank you, @kgryte!

**Comment by Planeshifter** [comment] 2022-08-30 19:52
Patches have meanwhile been released for the affected `blas` packages. The problem should now be resolved when installing `@stdlib/stats-chi2gof` anew.

**Closed as completed** 2022-08-30 19:53 UTC
Labels: Bug, Native Addons
