### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/ahaversin`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#1420] opened 2024-02-29 20:43 UTC
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/ahaversin`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/ahaversin/).

```c
double stdlib_base_ahaversin( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Userf1995** [comment] 2024-02-29 20:47
I would like to work on this issue, please assign.

**Comment by Pranavchiku** [comment] 2024-03-01 07:41
Go ahead, assigned it to you.

**Comment by Shashankss1205** [comment] 2024-03-01 17:31
I have completely understood the issue,
Kindly assign it to me, if no PR is made.

**Comment by Pranavchiku** [comment] 2024-03-01 17:34
@Shashankss1205 let @Rejoan-Sardar try and if is unable you may proceed, till then you can check #1433 if you wish

**Comment by Shashankss1205** [comment] 2024-03-03 16:13
@Pranavchiku If the Issue is still pending to be resolved, I am more than happy to work on it.

**Comment by Userf1995** [comment] 2024-03-04 04:23
almost done with it bro , I will update my PR

**Comment by Pranavchiku** [comment] 2024-03-04 04:37
@Shashankss1205 there are other good first issues you may look at. Also, we'll prefer to have #1670, and #1671 merged before you work on other PRs.

**Comment by Shashankss1205** [comment] 2024-03-04 07:50
Okay @Pranavchiku , I would wait for those 2 PRs to get merged, uptill then I'll take a look over the Machine Learning packages , because that's my favourite domain.

**Closed as completed** 2024-03-12 13:24 UTC
Labels: RFC, Feature, Math, Native Addons, Good First Issue, priority: Normal, C, difficulty: 2
