### ISSUE TITLE
`No such file or directory` error thrown when pushing a .c extension file with a 'newline at the end'.

### ISSUE THREAD

**Issue by Shashankss1205** [stdlib-js/stdlib#1712] opened 2024-03-05 15:29 UTC
### Description

I am not sure if this is a linting error or a different error or my lack of understanding but Please guide me out of this problem.
Encountered an error when adding a newline at the end of c files and pushing it to the Repository, while contributing to some feature changes.
![Screenshot from 2024-03-05 20-01-12](https://github.com/stdlib-js/stdlib/assets/123410790/805fc8e5-4206-46ac-9af2-b6185aeeba85)
Please take a look at this and help me sort this out.
Thank You!!

### Related Issues

None

### Questions

No.

### Reproduction

```shell
- Select any function say math/base/special
- Change the .c files to contain a newline at the end.
- Push the commit to the repo
```

### Expected Results

```shell
No errors are to be expected.
```

### Actual Results

```shell
Error is thrown, shown in the screenshot
```

### Version

current version

### Environments

Node.js

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by Pratik772846** [comment] 2024-03-05 15:53
I was facing this similar error with math/base/special/min package, but after [this](https://github.com/stdlib-js/stdlib/commit/d829b759e2910479911a3998c065b2cf2abf491e) commit, it was fixed. A similar kind of change is also needed in the math/base/special/max package also.

**Comment by Pratik772846** [comment] 2024-03-05 15:57
@kgryte PRs whose all tests have not been passed have been merged. I think we are getting these errors due to this reason.

**Comment by Shashankss1205** [comment] 2024-03-05 16:40
> I was facing this similar error with math/base/special/min package, but after [this](https://github.com/stdlib-js/stdlib/commit/d829b759e2910479911a3998c065b2cf2abf491e) commit, it was fixed. A similar kind of change is also needed in the math/base/special/max package also.

Mine all tests passed as soon as I removed the extra newlines so I took that way out of this problem.

**Comment by Pranavchiku** [comment] 2024-03-06 06:12
Everything works well for me, @Shashankss1205 you will have to add `#include <stdlib.h>` header in `example.c` created by you.

**Comment by Shashankss1205** [comment] 2024-03-06 06:57
> Everything works well for me, @Shashankss1205 you will have to add `#include <stdlib.h>` header in `example.c` created by you.

Okay thanks, I will add the header file and check the code once.

**Comment by Shashankss1205** [comment] 2024-03-09 12:14
Hello @Pranavchiku , can you please guide me onto how can I remove the error:
![Screenshot from 2024-03-09 17-32-32](https://github.com/stdlib-js/stdlib/assets/123410790/a49d7179-f97f-4e9c-b760-f6a3002d8ad5)
I got inactive because I couldn't figure out how to remove this error as it peeked in each and every time.
Please help so that I can again start contributing.

**Comment by kgryte** [comment] 2024-03-18 05:25
@Shashankss1205 Can you provide a reproducible example? Showing screenshots is not enough to help us debug. We need to be able to actually see the code you are trying to push. If you need to bypass Git hooks, append `--no-verify` when attempting `git push`.

**Comment by Shashankss1205** [comment] 2024-03-18 05:33
@kgryte thank you for your response, I have finally debugged this problem and it wasn't actually a problem of the package but mine personal execution problem.

Thank you for your valuable feedback.

**Comment by kgryte** [comment] 2024-03-18 06:13
@Shashankss1205 Thanks for the update. I'll go ahead and close this then.

**Closed as completed by kgryte** 2024-03-18 06:13 UTC
